pipeline {
    agent any
    
    parameters {
        booleanParam(defaultValue: false, description: "enable service?", name: "myBoolean")

    }

    stages {
        stage("Demo") {
            steps {
                echo "booleanParam is set to: ${params.myBoolean}"

            }
        }
    }
}