pipeline {
    agent any

    stages {
        stage("SCM Check IN") {
            steps {
                git 'https://github.com/punehim/Jenkins_Upgradev3.git'
            }
        }
        stage("Install") {
            steps {
                 bat 'mvn -f java-tomcat-sample/pom.xml clean install'
            }
        }
        stage("Package") {
            steps {
                bat 'mvn -f java-tomcat-sample/pom.xml package'
            }
        }
        stage("Artifacts Archiving") {
            steps {
                archiveArtifacts artifacts: '**/*.war', followSymlinks: false
            }
        }
    }
}